import {
  SiPython,
  SiSwift,
  SiTypescript,
  SiJavascript,
  SiCplusplus,
  SiC,
  SiHtml5,
  SiCss,
  SiNextdotjs,
  SiReact,
  SiFastapi,
  SiNestjs,
  SiPytorch,
  SiTensorflow,
  SiKeras,
  SiOpencv,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiLangchain,
  SiPostgresql,
  SiDocker,
  SiFirebase,
  SiRender,
  SiTailwindcss,
  SiGit,
  SiFramer,
} from "react-icons/si";
import { Code2 } from "lucide-react";
import type { IconType } from "react-icons";

const ICON_MAP: Record<string, IconType> = {
  python: SiPython,
  swift: SiSwift,
  typescript: SiTypescript,
  javascript: SiJavascript,
  "c++": SiCplusplus,
  c: SiC,
  html: SiHtml5,
  css: SiCss,
  "next.js": SiNextdotjs,
  react: SiReact,
  fastapi: SiFastapi,
  swiftui: SiSwift,
  nestjs: SiNestjs,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  keras: SiKeras,
  opencv: SiOpencv,
  "scikit-learn": SiScikitlearn,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  langchain: SiLangchain,
  postgresql: SiPostgresql,
  docker: SiDocker,
  firebase: SiFirebase,
  firestore: SiFirebase,
  render: SiRender,
  "tailwind css": SiTailwindcss,
  tailwindcss: SiTailwindcss,
  git: SiGit,
  framer: SiFramer,
  "framer motion": SiFramer,
};

export function getSkillIcon(skill: string): IconType {
  const key = skill.toLowerCase().trim();
  return ICON_MAP[key] ?? Code2;
}
